### ISSUE TITLE
ruamel.yaml not installed by requirements.txt

### ISSUE THREAD

**Issue by lriley2020** [TwoSails/WeatherDashboard#10]
After installing the packages in requirements.txt, when `python3 manage.py migrate` is run, I get the error `ModuleNotFoundError: No module named 'ruamel'`. Does `ruamel.yaml` need to be added to requirements.txt?

**Comment by lriley2020** [comment]
Update: the script runs after `django_plotly_dash` and `ruamel.yaml` are installed manually

**Comment by TwoSails** [comment]
Thank you for making me aware of those two missing requirements...
I have added them in the latest commit: [#7c01d45](https://github.com/TwoSails/WeatherDashboard/commit/7c01d4513ff5f54c7b6edcda6ddbdf0b1442a4c9)
If this error occurs again, feel free to make a pull request, it is great appreciated as I am aware that I have made a few errors while making the project open source.

This was just a side project of mine, so hope it works for you...
Happy Coding
